name: Build and Publish
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
      env:
        NODE_AUTH_TOKEN: ${{github.token}}
    - run: npm ci
    - run: npm run build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{github.token}}
